// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TCVShared.Data;

namespace TCVWeb.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20181001103604_Blog")]
    partial class Blog
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<int>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<int>("UserId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("TCVShared.Data.AccountLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Action");

                    b.Property<string>("LogData");

                    b.Property<DateTime>("LogTime");

                    b.Property<string>("RemoteIP")
                        .HasMaxLength(60);

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("LogTime");

                    b.HasIndex("UserId");

                    b.ToTable("AccountLog");
                });

            modelBuilder.Entity("TCVShared.Data.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("TCVShared.Data.AppSetting", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64);

                    b.Property<string>("Value")
                        .IsRequired();

                    b.HasKey("Name");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("TCVShared.Data.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("CreateIP")
                        .HasMaxLength(60);

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("IsLocked");

                    b.Property<DateTime?>("LastLogin");

                    b.Property<string>("LastLoginIP")
                        .HasMaxLength(60);

                    b.Property<DateTime?>("LastUpdate");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<DateTime?>("OpenTime");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<int>("Status");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UpdateUser")
                        .HasMaxLength(128);

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("TCVShared.Data.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AlbumId");

                    b.Property<string>("Content");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(128);

                    b.Property<string>("ExtLink")
                        .HasMaxLength(1024);

                    b.Property<int>("Format");

                    b.Property<string>("Image")
                        .HasMaxLength(512);

                    b.Property<DateTime?>("LastUpdate");

                    b.Property<string>("Preview")
                        .HasMaxLength(1024);

                    b.Property<DateTime?>("PublishTime");

                    b.Property<int>("Status");

                    b.Property<int?>("ThreadId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<string>("UpdateUser")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("ThreadId");

                    b.ToTable("BlogPosts");
                });

            modelBuilder.Entity("TCVShared.Data.BlogPostTaxo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("PostId");

                    b.Property<int>("TaxoId");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("TaxoId");

                    b.ToTable("BlogPostTaxoes");
                });

            modelBuilder.Entity("TCVShared.Data.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("FullName")
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Campaign");
                });

            modelBuilder.Entity("TCVShared.Data.MediaAlbum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("Description")
                        .HasMaxLength(256);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("MediaAlbums");
                });

            modelBuilder.Entity("TCVShared.Data.MediaFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AlbumId");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("FileName")
                        .HasMaxLength(128);

                    b.Property<int>("FileSize");

                    b.Property<string>("FullPath")
                        .HasMaxLength(512);

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("MediaFiles");
                });

            modelBuilder.Entity("TCVShared.Data.ShopAttrib", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.HasKey("Id");

                    b.ToTable("ShopAttrib");
                });

            modelBuilder.Entity("TCVShared.Data.ShopItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AlbumId");

                    b.Property<string>("Content");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<string>("Image")
                        .HasMaxLength(512);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("Packaging");

                    b.Property<string>("Preview")
                        .HasMaxLength(1024);

                    b.Property<double>("RegularPrice");

                    b.Property<string>("SKU")
                        .HasMaxLength(32);

                    b.Property<double>("SalePrice");

                    b.Property<string>("Specifications");

                    b.Property<int>("Status");

                    b.Property<int?>("ThreadId");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("Name");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.HasIndex("ThreadId");

                    b.ToTable("ShopItem");
                });

            modelBuilder.Entity("TCVShared.Data.ShopItemAttrib", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AttrId");

                    b.Property<bool>("IsRequired");

                    b.Property<int>("ItemId");

                    b.Property<string>("Values");

                    b.HasKey("Id");

                    b.HasIndex("AttrId");

                    b.HasIndex("ItemId");

                    b.ToTable("ShopItemAttrib");
                });

            modelBuilder.Entity("TCVShared.Data.ShopItemTaxo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ItemId");

                    b.Property<int>("TaxoId");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("TaxoId");

                    b.ToTable("ShopItemTaxo");
                });

            modelBuilder.Entity("TCVShared.Data.Taxonomy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<int?>("ParentId");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("Name", "Type");

                    b.ToTable("Taxonomies");
                });

            modelBuilder.Entity("TCVShared.Data.UserMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<DateTime?>("CreateTime");

                    b.Property<int>("Like");

                    b.Property<int?>("ParentId");

                    b.Property<int>("Rating");

                    b.Property<int>("Status");

                    b.Property<int>("ThreadId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("ThreadId");

                    b.HasIndex("UserId");

                    b.ToTable("UserMessages");
                });

            modelBuilder.Entity("TCVShared.Data.UserThread", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreateTime");

                    b.Property<int>("MsgCount");

                    b.Property<float>("TotalRating");

                    b.HasKey("Id");

                    b.ToTable("UserThreads");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("TCVShared.Data.AppRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("TCVShared.Data.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("TCVShared.Data.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("TCVShared.Data.AppRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TCVShared.Data.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("TCVShared.Data.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TCVShared.Data.AccountLog", b =>
                {
                    b.HasOne("TCVShared.Data.AppUser", "AppUser")
                        .WithMany("AccountLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TCVShared.Data.BlogPost", b =>
                {
                    b.HasOne("TCVShared.Data.MediaAlbum", "MediaAlbum")
                        .WithMany()
                        .HasForeignKey("AlbumId");

                    b.HasOne("TCVShared.Data.UserThread", "Thread")
                        .WithMany()
                        .HasForeignKey("ThreadId");
                });

            modelBuilder.Entity("TCVShared.Data.BlogPostTaxo", b =>
                {
                    b.HasOne("TCVShared.Data.BlogPost", "BlogPost")
                        .WithMany("Taxonomies")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TCVShared.Data.Taxonomy", "Taxonomy")
                        .WithMany()
                        .HasForeignKey("TaxoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TCVShared.Data.MediaAlbum", b =>
                {
                    b.HasOne("TCVShared.Data.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("TCVShared.Data.MediaFile", b =>
                {
                    b.HasOne("TCVShared.Data.MediaAlbum", "MediaAlbum")
                        .WithMany("MediaFiles")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TCVShared.Data.ShopItem", b =>
                {
                    b.HasOne("TCVShared.Data.MediaAlbum", "MediaAlbum")
                        .WithMany()
                        .HasForeignKey("AlbumId");

                    b.HasOne("TCVShared.Data.UserThread", "Thread")
                        .WithMany()
                        .HasForeignKey("ThreadId");
                });

            modelBuilder.Entity("TCVShared.Data.ShopItemAttrib", b =>
                {
                    b.HasOne("TCVShared.Data.ShopAttrib", "ShopAttrib")
                        .WithMany()
                        .HasForeignKey("AttrId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TCVShared.Data.ShopItem", "ShopItem")
                        .WithMany("Attributes")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TCVShared.Data.ShopItemTaxo", b =>
                {
                    b.HasOne("TCVShared.Data.ShopItem", "ShopItem")
                        .WithMany("Taxonomies")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TCVShared.Data.Taxonomy", "Taxonomy")
                        .WithMany()
                        .HasForeignKey("TaxoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TCVShared.Data.Taxonomy", b =>
                {
                    b.HasOne("TCVShared.Data.Taxonomy", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("TCVShared.Data.UserMessage", b =>
                {
                    b.HasOne("TCVShared.Data.UserMessage", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.HasOne("TCVShared.Data.UserThread", "Thread")
                        .WithMany("Children")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TCVShared.Data.AppUser", "AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
